const fs = require('fs');
const content = [
  "import { NextIntlClientProvider } from 'next-intl';",
  "import { getMessages } from 'next-intl/server';",
  "import Header from '@/components/Header';",
  "import Footer from '@/components/Footer';",
  "",
  "export function generateStaticParams() {",
  "  return [{ locale: 'en' }, { locale: 'zh' }];",
  "}",
  "",
  "export default async function LocaleLayout({",
  "  children,",
  "  params,",
  "}: {",
  "  children: React.ReactNode;",
  "  params: Promise<{ locale: string }>;",
  "}) {",
  "  const { locale } = await params;",
  "  const messages = await getMessages();",
  "",
  "  return (",
  "    <html lang={locale} className=\"dark\">",
  "      <body className=\"min-h-screen bg-gray-950 text-white antialiased\">",
  "        <NextIntlClientProvider messages={messages}>",
  "          <Header locale={locale} />",
  "          <main className=\"mx-auto max-w-7xl px-4 py-8 sm:px-6\">{children}</main>",
  "          <Footer locale={locale} />",
  "        </NextIntlClientProvider>",
  "      </body>",
  "    </html>",
  "  );",
  "}",
  ""
].join("\n");
fs.writeFileSync("D:/网站/src/app/[locale]/layout.tsx", content);
console.log("layout.tsx written");
